### ISSUE TITLE
Hardcoded random interval

### ISSUE THREAD

**Issue by kukovecz** [itsron717/XKCD#7]
Hi,

Neat project :)

However, when you use the --random option, it will always get a comic between ID 100 and 999.
I've created a branch when I have corrected it, but it says I don't have permission to push a new branch.

Can you correct it, or grant permission to push changes into a new branch and create pull request?

Thanks in advance!

**Comment by itsron717** [comment]
Hey!
Can you directly create a pull request on the master branch? I'd like all the contributions on the master branch itself.

**Comment by kuko01** [comment]
The working of the pull request is this:
  1) you have a master branch, you dont commit / push to master branch
  2) some contributor creates a branch from master, let's call it **side_branch**. Commits changes to that branch and pushes that branch into github.
  3) then the contributor can create a pull request, in which it is requested to move the content from the **side_branch** to the master. When you accept it, the **side_branch** can be deleted and there is 1 new commit in the master: the merge commit.

(sorry for the long tale if you already familiar with git)

I created a branch and when I tried to push it, the remote refused saying that I don't have permission for it. That's why I told you to correct this bug or enable pushing new branches.
